[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sbi"
description = " Simulation-based inference in JAX"
authors = [{name = "Simon Dirmeier", email = "sfyrbnd@pm.me"}]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/dirmeier/lfi"
keywords = ["abc", "simulation-based inference", "approximate Bayesian computation", "normalizing flows", "smc-abc"]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
requires-python = ">=3.8"
dependencies = [
    "blackjax>=0.9.6",
    "distrax>=0.1.2",
    "dm-haiku>=0.0.9",
    "flax>=0.6.3",
    "optax>=0.1.3",
]
dynamic = ["version"]

[project.urls]
homepage = "https://github.com/dirmeier/sbi"

[tool.hatch.version]
path = "sbi/__init__.py"

[tool.hatch.build.targets.sdist]
exclude = [
    "/.github",
    "./gitignore",
    "/.pre-commit-config.yaml"
]

[tool.hatch.envs.default]
dependencies = [
    "pre-commit>=2.20.0",
    "black>=22.8.0",
    "flake8>=5.0.4",
    "flake8-pyproject>=1.1.0.post0",
    "isort>=5.10.1",
    "mypy>=0.971",
    "bandit>=1.7.4",
    "pytest>=7.2.0",
    "pytest-cov>=4.0.0"
]

[tool.hatch.envs.default.scripts]
test = 'pytest -v --doctest-modules --cov=./sbi --cov-report=xml sbi tests'

[tool.black]
line-length = 80
extend-ignore = "E203"
target-version = ['py39']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''


[tool.isort]
profile = "black"
line_length = 80
include_trailing_comma = true

[tool.flake8]
max-line-length = 80
extend-ignore = ["E203", "W503"]
